// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 29/04/2026, 19:36:27
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/rizwangustama/Documents/bangunind/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rizwangustama/Documents/bangunind/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rizwangustama/Documents/bangunind/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rizwangustama/Documents/bangunind/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rizwangustama/Documents/bangunind/app/plugins/**/*.{js,ts,mjs}","/Users/rizwangustama/Documents/bangunind/app/composables/**/*.{js,ts,mjs}","/Users/rizwangustama/Documents/bangunind/app/utils/**/*.{js,ts,mjs}","/Users/rizwangustama/Documents/bangunind/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/rizwangustama/Documents/bangunind/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/rizwangustama/Documents/bangunind/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/rizwangustama/Documents/bangunind/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;